### PR TITLE
Define and integrate `PValues` type

### PR DESCRIPTION
**Pull request by juliangehring**
Adds the `PValues` type that represents a vector of p-values. Benefits of working with this specialised type instead with a simple vector of floats:
- More meaningful dispatch, especially when a method can work with different inputs (e.g. p-values vs z-scores)
- Validity checking is integrated into the constructor, instead of having to use a separate function explicitly
- Properties of the p-values have to be computed only once: minimum and maximum; these are part of the validity check anyway
- The type is based on the `AbstractVector`, and hence all vector operations work naturally without the need to redefine standard methods

Uses the `PValues` type for all relevant methods. A fallback for p-values in the form of a vector of floats ensures backwards compatibility.

Examples:
```julia
v = [0.001, 0.01, 0.1, 0.5]

## new features
pv = PValues(v)
extrema(pv)  # no recomputation needed
adjust(pv, Sidak())
estimate_pi0(pv, Storey())

## old behaviour
adjust(v, Sidak())
estimate_pi0(v, Storey())
```

### CODE REVIEW

**Comment by juliangehring** [comment]
WIP

**Comment by juliangehring** [comment]
Open question: Should methods, such as `adjust`, also return p-values as `PValues`?

**Comment by nignatiadis** [comment]
Nice! 

Regarding the open question, I'd say probably no. Later on we might end up with methods returning more complicated types, but I think `adjust` should remain as simple as possible and behave as it does now regarding output type (since it's the "entry" point function for most users of the package).

**Comment by juliangehring** [comment]
For other packages, the new output type should not make a difference: It behaves like a vector of floats.

**Comment by nignatiadis** [comment]
Hmm I still don't like it. p-values come with some distributional guarantees and adjusted p-values definitely don't satisfy these, so I'd be very hesitant to wrap adjusted p-values in a `PValues` type. We could add a `AdjustedPvalues` type, but I don't see the advantage.

**Pull request merged**
