### PR TITLE
Higher criticism scores and critical value estimation

### PR DESCRIPTION
**Pull request by juliangehring**
This adds higher criticism scores and critical value estimation, as described in:
Donoho, D., and Jin, J. (2008). Higher criticism thresholding: Optimal feature selection when useful features are rare and weak. PNAS 105, 14790–14795.
Klaus, B., and Strimmer, K. (2013). Signal identification for rare and weak features: higher criticism or false discovery rates? Biostatistics 14, 129–143.

### CODE REVIEW

**Comment by juliangehring** [comment]
I had this lying around for a while, mostly because I haven't found a good interface for these functions so far. @nignatiadis Do you have ideas how we could integrate this?

**Comment by nignatiadis** [comment]
That is an interesting question and I was thinking about it too. It is also related to #48.

I mostly think of Higher Criticism as a global test too (in that case people usually return the higher criticism score at the maximum index, rather than the p-value and they call this the higher criticism statistic). It has some nice optimality properties, but it is a pain to convert this statistic to an actual p-value (I guess simulation would work though), see e.g. https://academic.oup.com/biomet/article/101/4/964/1775753. It almost seems like a HypothesisTests.jl interface would be nicest, which only calculates a p-value in a 2nd step.

I guess in Bernd's paper this takes more a of classification perspective, which would again need a different interface..

**Comment by juliangehring** [comment]
Can we use the HC as an estimator for π0? I remember reading this in the discussion of one of the HC papers, but I have never seen it used practically.

**Comment by nignatiadis** [comment]
Do you have a reference for that? I don't think I have ever seen such a π0 estimator.

**Comment by juliangehring** [comment]
Let me go through the papers again and have a look.
But if it isn't a commonly known or used method, I wouldn't bother implementing it.

**Comment by juliangehring** [comment]
How about:
- Define the types `HigherCriticismScore` and  `HigherCriticalValue`, similar to the other methods we already have.
- Add and export `estimate(x::Pvalues, method)` for the two types that wraps the lower-level functions. `estimate` can be extended from `Distributions` and we avoid clashes with other packages that define the same method (see #48).

This way, we leverage our existing interface, and users can apply the statistics however they like.

**Comment by juliangehring** [comment]
@nignatiadis What are your thoughts?

**Comment by nignatiadis** [comment]
Hello Julian, I think that is a good way to go for now! Does Bernd/fdrtools use the term `HigherCriticalValue`?

**Comment by juliangehring** [comment]
The term "higher critical value" isn't used in the papers mentioned above. We could rename the method to e.g. `HigherCriticismThreshold` to be more in line with the existing literature.

**Pull request merged**
