### PR TITLE
Collect reference publications

### PR DESCRIPTION
**Pull request by juliangehring**
What would science be without citing the papers that describe the methods?

### CODE REVIEW

**Comment by nignatiadis** [comment]
Haha nice! I also had not seen the derivations for the exact bootstrap for Storey's bootstraped estimator.

**Comment by juliangehring** [comment]
This should cover the original papers for the methods. These may always be the most informative ones, and it could be nice to also add some comprehensive reviews as well (which may be easier to access or to read in some cases).

**Comment by juliangehring** [comment]
Yes, the closed form bootstrap makes it so much simpler and nicer to use.

**Comment by juliangehring** [comment]
My longer term goal is to reference the methods in the documentation of the respective types.

**Comment by juliangehring** [comment]
Should the references also includes DOIs and URLs?

**Pull request merged**
