### PR TITLE
Various general tweaks and simplifications

### PR DESCRIPTION
**Pull request by juliangehring**
Collection of smaller improvements

### CODE REVIEW

**Comment by nignatiadis** [comment]
Nice! I have wanted to switch all `n`'s to `m`'s for some time actually (because this seems to be the convention used in most FDR related papers), but maybe this can wait for another day. In R's `p.adjust` it is also called `n`, but I still prefer `m`. 

As a side note that's also another feature we could add,  i.e. also allow `m` as function input similar to `p.adjust` for cases where only part of the p-values (say the ones below 0.001) are available.

**Comment by juliangehring** [comment]
I don't feel too strongly about the naming - whatever works in the end. It will become more interesting once we have a documentation with formulas.

**Comment by juliangehring** [comment]
Good point about specifying n|m for the adjustments, this feature is also somewhere on my to-do list

**Comment by nignatiadis** [comment]
Ok great, let's revisit it when we have documentation with formulas! And regarding `n/m`, I realized it was missing while implementing https://github.com/juliangehring/MultipleTesting.jl/pull/29, since I think for that method you really need all p-values and not just the small ones (+`m`).

**Pull request merged**
