### PR TITLE
Simplify Benjamini-Liu step

### PR DESCRIPTION
**Pull request by juliangehring**
- Drop the impossible edge case
- Simplify and save some precious bit operations ;)

### CODE REVIEW

**Comment by juliangehring** [comment]
Nice side effect: We have 100% test coverage now ;)

**Comment by nignatiadis** [comment]
In the old version I introduced a bug for sure, it should be returning `1.0`.  I think there might be some instances where this actually happens (? did not think too much about it).

**Comment by juliangehring** [comment]
I don't see how `-(1-p)^(n-i+1)` can become positive: It is 0 for p=0 and negative for all other values of p. Is there more to it?

**Comment by nignatiadis** [comment]
Dohh I was looking at P_(i) <= 1- [1 - min(1, m/(m-i+1)α)]^{1/(m-i+1)} and taking a special case for the `min`. But you are right of course.

**Comment by juliangehring** [comment]
Okay, so do we need more changes for this?

**Comment by nignatiadis** [comment]
Nope looks good!

**Pull request merged**
