### PR TITLE
Fun with type system!

### PR DESCRIPTION
**Pull request by nignatiadis**
This is not directly useful, but I thought it was fun/cute to use the type system to express what type-I error the different adjustment methods control.

### CODE REVIEW

**Comment by julian-gehring** [comment]
Look interesting. Are there any obvious downsides to having such parametric types?

**Comment by julian-gehring** [comment]
I don't think that this really is a problem here, but perhaps good to keep in the back of our heads: https://julia.readthedocs.org/en/latest/manual/performance-tips/#avoid-containers-with-abstract-type-parameters

**Comment by nignatiadis** [comment]
Hmm, I don't know enough about the type system to be able to say so, but I would not think so? Also right now it is a purely cosmetic change since we don't have any methods dispatching on the abstract type PValueAdjustmentMethod (always on the concrete ones). 

Going beyond this pull request: This was motivated also by having methods for k-FWER control (probability of doing >= k false rejections). So something like the below (does not work right now - not sure why- but this is the idea):

```julia
type FWER{k} <: GeneralizedTypeOneError
end

type GeneralizedBonferroni{k} <: PValueAdjustmentMethod{FWER{k}}
end

adjust{k<: Int64}(pvals, method::GeneralizedBonferroni{k} ) = min(pValues * length(pValues) / k, 1.)

#adjust(pvals, GeneralizedBonferroni{k}())
```
I think it would be elegant to separate type-I error from algorithms, but it might be overkill and it probably is easier to just have `k` be a field of `GeneralizedBonferroni`.

**Comment by nignatiadis** [comment]
Closing this since it just overuses the type-system for no real gain. Instead eventually we could have maybe functions along the lines of

` guarantee(BenjaminiHochberg()) = :FDR`

`controls_FDR(    BenjaminiHochberg()) = true`

**Pull request closed without merging**
